### ISSUE TITLE
ios support 

### ISSUE THREAD

**Issue by naeluh** [jeromeetienne/WebAR#2]
Hi Jerome , 

This is really great !

I was thinking about using this for a project , and was wondering what ios support is for WebAR?

Let me know if I can clarify.

thanks !

Nick

**Comment by jeromeetienne** [comment]
Unfortunatly, it isnt possible currently. 

Apple is working on WebRTC tho -https://webkit.org/status/#specification-webrtc . As soon as they are done, this project will work on ios. 

Let's hope they join the party asap :)

**Comment by naeluh** [comment]
Cool thanks !

**Comment by jarodium** [comment]
Itching to use this on Phonegap are we? Me too xD ehehehheeh

**Comment by evhan55** [comment]
So sad :(
